sportsproject/sportapp/urls.py
from django.urls import path

from . import views
from  django.urls import path
app_name='sportapp'
urlpatterns = [
    path('',views.index,name='index'),
    path('football/<int:football_id>/',views.detail,name='detail'),
    path('add/',views.add_football,name='add_movie'),
    path('update/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/',views.delete,name='delete'),
]

sportsproject/sportsproject/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("sportapp.urls"))
]
if settings.DEBUG:
    urlpatterns+=static( settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sportsproject/sportapp/models.py
from django.db import models

# Create your models here.
class Football(models.Model):
    name= models.CharField(max_length=100)
    desc=models.TextField()
    club=models.CharField(max_length=100)
    bdor=models.IntegerField()
    img=models.ImageField(upload_to='gallery')

    def __str__(self):
        return self.name

sportsproject/sportapp/forms.py
from django import forms
from . models import Football

class FootballForm(forms.ModelForm):
    class Meta:
        model=Football
        fields=['name','desc','club','bdor','img']

sportsproject/sportapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from . models import Football
from . forms import FootballForm
# Create your views here.
def index(request):
    football=Football.objects.all()
    context={
        'footballer':football
    }
    return render(request,'index.html',context)

def detail(request,football_id):
    football=Football.objects.get(id=football_id)
    return render(request,"detail.html",{'football':football})

def add_football(request):
    if request.method=="POST":
        name=request.POST.get('name')
        desc=request.POST.get('desc')
        club=request.POST.get('club')
        bdor=request.POST.get('bdor')
        img=request.FILES['img']
        football=Football(name=name,desc=desc,club=club,bdor=bdor,img=img)
        football.save
    return render(request,'add.html')

def update(request,id):
    football=Football.objects.get(id=id)
    form=FootballForm(request.POST or None,request.FILES,instance=football)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request,'edit.html',{'form':form,'football':football})

def delete(request,id):
    if request.method=="POST":
        football = Football.objects.get(id=id)
        football.delete()
        return redirect('/')
    return render(request,'delete.html')

sportsproject/templates/add.html
{% extends 'base.html' %}
{% block body %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="text" name="name" placeholder="Enter Name"><br>
    <input type="text" name="desc" placeholder="Enter Player Desc"><br>
    <input type="text" name="club" placeholder="Enter Club"><br>
    <input type="number" name="bdor" placeholder="Enter Balon D'or"><br>
    <input type="file" name="img" placeholder="Insert image"><br>
    <input type="submit" >
</form>
{% endblock %}

sportsproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<!-- Just an image -->
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">
      Balon D'or Winners
<!--    <img src="/docs/4.0/assets/brand/bootstrap-solid.svg" width="30" height="30" alt="">-->
  </a>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

sportsproject/templates/delete.html
{% extends 'base.html' %}
{% block body %}

<form method="POST">
    {% csrf_token %}
    Are you Sure?
    <input type="Submit">
</form>
{% endblock %}

sportsproject/templates/detail.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img src="{{football.img.url}}" width="100" height="100">
        </div>
        <div class="col-md-6">
            {{football.name}}<br>
            <h6>{{football.desc}}</h6> <br>
            Club: {{football.club}}<br>
            Balon D'or: {{football.bdor}}<br>
            <a class="btn btn-warning" href="{% url 'sportapp:update' football.id %}">update</a>
            <a class="btn btn-danger" href="{% url 'sportapp:delete' football.id %}">delete</a>
        </div>
    </div>
</div>


{% endblock %}

sportsproject/templates/edit.html
{% extends 'base.html' %}

{% block body %}
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit">

</form>
{% endblock %}

sportsproject/templates/index.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-3">
            {% for i in footballer %}
            <div class="card" style="width: 18rem;">
                <img class="card-img-top" src="{{i.img.url}}" alt="Card image cap" width="100px" height="250px">
                    <div class="card-body">
                        <h5 class="card-title">{{i.name}}</h5>
<!--                                <p class="card-text">{{i.desc}}</p>-->
                        <a href="{% url 'sportapp:detail' i.id %}" class="btn btn-primary">details...</a>
                    </div>
                </div>
            </div>
        </div>
    </div>

<!--<img src ="{{i.img.url}}" width="100" height="100">-->
<!--<a href="{% url 'sportapp:detail' i.id %}">{{i.name}}<br>-->
<!--{% endfor %}-->
<!--{% endblock %}-->